### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by auguster** [razorgirl/nzedb-docker#1]
Hello,

Nice work on this dockerfile, you saved me quite a lot of time to test nZEDb. It's so much faster than regular newznab (haven't tried nn+ though).
1. I noticed there is a minor error in your dockerfile, line 105, there is 
   `chown www-data:www-data nZEDb/www -R`
   followed by
   `chmod 777 /var/www/nZEDb/libs/smarty/templates_c && \`
   the `&& \` should be moved from end of line 106 to end of line 105.
2. I also had to `mkdir /var/lib/php5/session`
3. I'm not sure that the last line of the Dockerfile for cleanup frees any space. If I understood well, docker stacks the filesystem's differences of each command. So the file you deleted in the last step are still present in the intermediary layers. So the size of the resulting container should not change with or without this step.
4. I'm not sure what the SSH Access is for, you know you can enter your running container through `docker exec -it nZEDb /bin/bash` ?

Anyway, great work putting everything in a container ! The fun part is trying to decrease the overall container size now (1.62GB for me) ;-)

**Comment by razorgirl** [comment]
Sorry for this truly late reply. I'm going to look into it. Also, now that there's `docker-compose`, I'll probably rework the whole shebang to have this running in true Docker style, one service per container, ditching Ubuntu bloat for Alpine.

Regarding your cleanup comments: it's best practice to clean up after yourself, hence the commands. There's arguably a lot more to be done to truly reduce the container footprint. Once you flatten the image, those savings will be apparent.

**Comment by auguster** [comment]
No worries, I haven't had the time to play with nzedb. But I'm willing to get back to it.
If I can be of use to help in developing your project don't hesitate.

Concerning docker compose, I deploy the services on CoreOS which works with systemd units instead of docker compose. So I prefer not to use the later. But it's easy to write systemd units from docker compose files.

**Comment by finish06** [comment]
Indeed, tmux will not run inside a `docker exec` instance... You must ssh into the docker instance...
Also, you are missing the `composer install` command within /var/www/nzedb/ directory.

**Comment by przemekk13** [comment]
I am getting failure:

`Removing intermediate container 836d094cb0cd
Step 28 : RUN mkdir /var/www &&   cd /var/www &&   git clone https://github.com/nZEDb/nZEDb.git &&   chmod 777 /var/www/nZEDb/libs/smarty/templates_c &&   chown www-data:www-data nZEDb/www -R
 ---> Running in db7838aba71e
Cloning into 'nZEDb'...
chmod: cannot access ‘/var/www/nZEDb/libs/smarty/templates_c’: No such file or directory
The command '/bin/sh -c mkdir /var/www &&   cd /var/www &&   git clone https://github.com/nZEDb/nZEDb.git &&   chmod 777 /var/www/nZEDb/libs/smarty/templates_c &&   chown www-data:www-data nZEDb/www -R' returned a non-zero code: 1
`

**Comment by EasternPA** [comment]
Same error here after about 10-15 minutes of build.

**Comment by EasternPA** [comment]
I was able to update this enough to build against the phusion/baseimage 0.9.13 using composer but the ubuntu.sh from kevinlekiller won't compile zend when using baseimage 0.9.19. User niel is actively working on rebuilding yenc tools that run with the latest other utils. I can post what I have so far but it fails on zend after nZEDb.

**Comment by OmgImAlexis** [comment]
@razorgirl any updates on this?

**Comment by razorgirl** [comment]
Today I have some free time and motivation, so I'm going to take a look into it. However, I wouldn't expect too much from this. nZEDb is a true clusterfuck of working, broken, in-development and abandoned parts. The last time I set an instance up (from scratch, by hand) on a FreeBSD system, I found the database to contain wrong entries that would break the login to the web interface completely. This should not happen with a clean install, ever. This also highlights the code quality, which is one of the worst I have seen in my career. There are tons of unsolved issues with processing and categorizing releases, it's a miracle it works at all. It is a commendable undertaking but it is such a patchwork of bits and pieces that I feel it should be reworked completely. From scratch, from the ground up, throwing away lots of current code, refactoring the rest. As this is a niche tool for niche users, I don't see this happening any time soon though.

That being said: as these are completely free and open source configuration files, why not get tinkering yourself? Do so many people expect to get everything they need for free and not giving back in the process? I spent my time (which is worth quite a lot these days) of my own volition but do not feel any responsibility to maintain it for others who did not participate. It's a work of passion — and lately I do not feel much passion for nZEDb and/or Docker any more.

I'm going to update this issue when there is anything to report. To get news about changes to the files, watch this repo.

**Comment by razorgirl** [comment]
@OmgImAlexis: I've just pushed the first iteration of a completely overhauled version which leverages Alpine Linux and docker-compose. I have tested this and it works for me. If you run into trouble, please open another issue where we can discuss further refinements.

Since this the issues raised are no longer applicable, I'm going to close this.
