### ISSUE TITLE
nZEDb PHP Dockerfile requires alpine:3.5

### ISSUE THREAD

**Issue by jeskoriesner** [razorgirl/nzedb-docker#9]
building php/Dockerfile does not build due to unsatisfied constraint for php5-imagick and php5-memcache. Those packages are now only available for alpine linux 3.4 and 3.5 (see https://pkgs.alpinelinux.org/packages?name=php5-imag*&branch=&repo=&arch=&maintainer=)
Same goes for nzedb/Dockerfile
Please update php/Dockerfile and nzedb/Dockerfile accordingly

**Comment by razorgirl** [comment]
Why don't you do it and send a pull request instead of complaining?

Anyway, as I lost interest in Docker because it's too Linux-centric for my taste, I will very probably not update this any longer.
